"""
Multi-page app shell (spec §12.10). A PaperLoom project is a set of pages
(skeletons, §7.1). On its own that gives you N independent windows; this module
emits the piece that makes them a coherent *app*:

    app.py          hosts every page in a QStackedWidget, exposes navigate(name),
                    owns the light/dark toggle, and is the entry point.
    app_logic.py    hand-written, never overwritten - where navigation handlers
                    and cross-page logic live.

So the generated result is an application you can actually run and click through,
not a folder of unrelated windows.
"""
from __future__ import annotations
import os


def _snake(name: str) -> str:
    return "".join("_" + c.lower() if c.isupper() else c for c in name).lstrip("_")


APP_TEMPLATE = '''"""
Auto-generated by PaperLoom. Do not edit by hand - regenerate from the design.

The application shell: every page is a screen in a stack, navigation is one call.
"""
import sys

from PySide6.QtWidgets import QApplication, QMainWindow, QStackedWidget, QWidget

import app_theme
{page_imports}

PAGES = [{page_names}]


class AppShell(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("{app_title}")
        self.resize({width}, {height})
        self.setStyleSheet(app_theme.stylesheet())

        self.stack = QStackedWidget(self)
        self.setCentralWidget(self.stack)

        # every page becomes a screen in the stack
        self.pages = {{}}
{page_setup}
        if PAGES:
            self.navigate(PAGES[0])

    def navigate(self, page_name):
        """Show a page by name. Returns True if the page exists."""
        widget = self.pages.get(page_name)
        if widget is None:
            return False
        self.stack.setCurrentWidget(widget)
        return True

    def toggle_theme(self):
        """Switch the whole app between light and dark."""
        return app_theme.toggle(self)


def main():
    app = QApplication(sys.argv)
    shell = AppShell()
    shell.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
'''

LOGIC_TEMPLATE = '''"""
Hand-written application logic for {app_title}.
PaperLoom will not overwrite this file.

Subclass or extend the generated shell here - navigation between pages, shared
state, anything that spans more than one screen.

    from app import AppShell

    class App(AppShell):
        def on_start(self):
            self.navigate("{first_page}")
"""
from app import AppShell


class App(AppShell):
    def __init__(self):
        super().__init__()
        # TODO: wire cross-page logic here.

    # example: called from a button on any page
    def go(self, page_name):
        return self.navigate(page_name)


if __name__ == "__main__":
    import sys
    from PySide6.QtWidgets import QApplication
    qt_app = QApplication(sys.argv)
    window = App()
    window.show()
    sys.exit(qt_app.exec())
'''


def generate_app_shell(project, backend, target_dir: str) -> dict:
    """Emit the multi-page shell for a project. `backend` is the PySide backend
    (already used to generate each page's ui module)."""
    gen_dir = os.path.join(target_dir, "generated", "pyside6")
    os.makedirs(gen_dir, exist_ok=True)

    imports, setup, names = [], [], []
    for page in project.pages:
        mod = f"{_snake(page.name)}_ui"
        imports.append(f"from {mod} import Ui_{page.name}")
        names.append(f'"{page.name}"')
        setup.append(
            f'        _{_snake(page.name)} = QMainWindow()\n'
            f'        Ui_{page.name}().setupUi(_{_snake(page.name)})\n'
            f'        _w = _{_snake(page.name)}.centralWidget() or _{_snake(page.name)}\n'
            f'        self.pages["{page.name}"] = _w\n'
            f'        self.stack.addWidget(_w)\n'
        )

    first = project.pages[0].name if project.pages else ""
    app_source = APP_TEMPLATE.format(
        page_imports="\n".join(imports),
        page_names=", ".join(names),
        page_setup="".join(setup) or "        pass\n",
        app_title=project.name or "App",
        width=project.pages[0].width if project.pages else 900,
        height=project.pages[0].height if project.pages else 600,
    )
    logic_source = LOGIC_TEMPLATE.format(
        app_title=project.name or "App", first_page=first)

    app_path = os.path.join(gen_dir, "app.py")
    logic_path = os.path.join(gen_dir, "app_logic.py")
    backend._write_generated(app_path, app_source)
    backend._write_logic_once(logic_path, logic_source)
    return {"app": app_path, "app_logic": logic_path}
