"""
C++ Qt Widgets codegen backend (spec §2.2a, §6). Mirrors the PySide backend's
structure but emits idiomatic C++ using Qt's own uic convention for the
round-trip split (§6.3):

  generated/cpp/ui_<page>.h    - the Ui_<Cls> struct with setupUi(); regenerated
                                 freely, never hand-edited.
  generated/cpp/<page>.h/.cpp  - hand-written QMainWindow subclass that owns a
                                 Ui_<Cls> and wires signals to slots; written
                                 once, never overwritten.
  generated/cpp/main.cpp       - entry point; written once.
  generated/cpp/CMakeLists.txt - so the emitted project actually builds; written
                                 once (it names the target after the page, which
                                 is stable).

Signals declared on a component become Qt slots on the hand-written class, wired
in the constructor via connect(). Widget member declarations are collected into
the generated header's struct so setupUi can assign them.
"""
from __future__ import annotations
import os
import textwrap

from .base import CodegenBackend, cpp_qt_prop_lines
from ..core.model import DesignPage
from ..core import sanitize

UI_HEADER_TEMPLATE = '''// Auto-generated by PaperLoom. Do not edit by hand - regenerate from the design instead.
#pragma once

#include <QMainWindow>
{includes}

class Ui_{cls} {{
public:
{member_decls}

    void setupUi(QMainWindow *MainWindow) {{
        MainWindow->setWindowTitle("{title}");
        MainWindow->resize({width}, {height});
{setup_body}
    }}
}};
'''

LOGIC_HEADER_TEMPLATE = '''// Hand-written logic header for {cls}.
// PaperLoom will not overwrite this file - regenerating only touches ui_{snake}.h.
#pragma once

#include <QMainWindow>
#include "ui_{snake}.h"

class {cls} : public QMainWindow {{
    Q_OBJECT
public:
    explicit {cls}(QWidget *parent = nullptr);

private slots:
{slot_decls}

private:
    Ui_{cls} ui;
}};
'''

LOGIC_SOURCE_TEMPLATE = '''// Hand-written logic for {cls}.
// PaperLoom will not overwrite this file.
#include "{snake}.h"
#include <QDebug>

{cls}::{cls}(QWidget *parent) : QMainWindow(parent) {{
    ui.setupUi(this);
{signal_wiring}
}}

{slot_defs}'''

MAIN_TEMPLATE = '''#include <QApplication>
#include "{snake}.h"

int main(int argc, char *argv[]) {{
    QApplication app(argc, argv);
    {cls} window;
    window.show();
    return app.exec();
}}
'''

CMAKE_TEMPLATE = '''cmake_minimum_required(VERSION 3.16)
project({project})

set(CMAKE_AUTOMOC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt6 REQUIRED COMPONENTS Widgets)

add_executable({project}
    main.cpp
    {snake}.cpp
)
target_link_libraries({project} PRIVATE Qt6::Widgets)
'''


def _snake(name: str) -> str:
    return "".join("_" + c.lower() if c.isupper() else c for c in name).lstrip("_")


class CppBackend(CodegenBackend):
    target = "cpp"

    def generate(self, page: DesignPage, target_dir: str) -> dict:
        self.warnings = []
        cls = page.name
        snake = _snake(page.name)

        setup_lines, member_decls, slot_decls, slot_defs, signal_lines = [], [], [], [], []
        used_classes = set()
        gen_dir = os.path.join(target_dir, "generated", "cpp")

        for dw in page.widgets:
            component = self.registry.get(dw.component_id)
            if component is None:
                continue
            qt_class = component.widget_class
            used_classes.add(component.qt_include)
            member_decls.append(f"    {qt_class} *{dw.object_name};")

            ctx = self._widget_context(dw, component)
            self._attach_asset(dw, ctx, gen_dir)
            fragment = component.render_cpp(ctx)
            if "QPixmap(" in fragment:
                used_classes.add("QPixmap")
            if "QMovie(" in fragment:
                used_classes.add("QMovie")
            if "QDate(" in fragment or "QDate::fromString(" in fragment:
                used_classes.add("QDate")
            if "QTime(" in fragment or "QTime::fromString(" in fragment:
                used_classes.add("QTime")
            if "QTreeWidgetItem(" in fragment:
                used_classes.add("QTreeWidgetItem")
            if "QFileInfo(" in fragment:
                used_classes.add("QFileInfo")
            setup_lines.append(textwrap.indent(fragment.strip("\n"), "        "))
            for line in cpp_qt_prop_lines(dw.object_name, getattr(dw, "qt_props", None)):
                setup_lines.append("        " + line)

            for sig in component.signals:
                slot = sig.stub.format(name=dw.object_name)
                signal_lines.append(
                    f"    connect(ui.{dw.object_name}, &{qt_class}::{sig.name}, "
                    f"this, &{cls}::{slot});"
                )
                slot_decls.append(f"    void {slot}();")
                slot_defs.append(
                    f'void {cls}::{slot}() {{\n'
                    f'    // TODO: implement.\n'
                    f'    qDebug() << "{dw.object_name} {sig.name}";\n'
                    f'}}\n'
                )

        # --- layouts ---
        layout_lines = []
        if page.layouts:
            for lg in page.layouts:
                lc = {"vbox": "QVBoxLayout", "hbox": "QHBoxLayout",
                      "grid": "QGridLayout", "form": "QFormLayout"}.get(lg.kind, "QVBoxLayout")
                used_classes.add(lc)
                parent = lg.parent or "MainWindow"
                layout_lines.append(f"        auto *{lg.id} = new {lc}({parent});")
                layout_lines.append(f"        {lg.id}->setSpacing({lg.spacing});")
                l, t, r, b = lg.margins
                layout_lines.append(f"        {lg.id}->setContentsMargins({l}, {t}, {r}, {b});")
                members = sorted(
                    [dw for dw in page.widgets if dw.layout_id == lg.id],
                    key=lambda w: (w.layout_row, w.layout_col))
                for dw in members:
                    if lg.kind == "grid":
                        layout_lines.append(
                            f"        {lg.id}->addWidget({dw.object_name}, "
                            f"{dw.layout_row}, {dw.layout_col});")
                    else:
                        layout_lines.append(
                            f"        {lg.id}->addWidget({dw.object_name});")
        if layout_lines:
            setup_lines.extend(["", "        // layouts"] + layout_lines)

        # --- connections ---
        for conn in (page.connections or []):
            sender = conn.sender if conn.sender == "MainWindow" else conn.sender
            receiver = conn.receiver if conn.receiver == "MainWindow" else conn.receiver
            sig = conn.signal.split("(")[0]
            sl = conn.slot.split("(")[0]
            signal_lines.append(f"        connect({sender}, &{type(None).__name__}::{sig}, {receiver}, &{type(None).__name__}::{sl});")

        # --- tab order ---
        if page.tab_order and len(page.tab_order) > 1:
            for i in range(len(page.tab_order) - 1):
                a, b = page.tab_order[i], page.tab_order[i + 1]
                setup_lines.append(f"        QWidget::setTabOrder({a}, {b});")

        includes = "\n".join(f"#include <{c}>" for c in sorted(used_classes))

        ui_header = UI_HEADER_TEMPLATE.format(
            cls=cls, title=sanitize.escape_string(page.title), width=page.width, height=page.height,
            includes=includes,
            member_decls="\n".join(member_decls) if member_decls else "    // no widgets",
            setup_body="\n".join(setup_lines) if setup_lines else "        (void)MainWindow;",
        )
        logic_header = LOGIC_HEADER_TEMPLATE.format(
            cls=cls, snake=snake,
            slot_decls="\n".join(slot_decls) if slot_decls else "    // no slots yet",
        )
        logic_source = LOGIC_SOURCE_TEMPLATE.format(
            cls=cls, snake=snake,
            signal_wiring="\n".join(signal_lines),
            slot_defs="\n".join(slot_defs),
        )
        main_source = MAIN_TEMPLATE.format(cls=cls, snake=snake)
        cmake_source = CMAKE_TEMPLATE.format(project=snake, snake=snake)

        # gen_dir computed above
        ui_path = os.path.join(gen_dir, f"ui_{snake}.h")
        header_path = os.path.join(gen_dir, f"{snake}.h")
        source_path = os.path.join(gen_dir, f"{snake}.cpp")
        main_path = os.path.join(gen_dir, "main.cpp")
        cmake_path = os.path.join(gen_dir, "CMakeLists.txt")

        # generated header: always overwritten
        self._write_generated(ui_path, ui_header)
        # everything hand-editable: written once, never clobbered
        self._write_logic_once(header_path, logic_header)
        self._write_logic_once(source_path, logic_source)
        self._write_logic_once(main_path, main_source)
        self._write_logic_once(cmake_path, cmake_source)

        return {
            "generated": ui_path,
            "logic": source_path,
            "logic_header": header_path,
            "main": main_path,
            "cmake": cmake_path,
        }
