"""
PySide6 codegen backend (spec §6, §2.2a). Walks a DesignPage, renders each
widget's PySide6 template fragment from the component library, indents it into
setupUi, and wires the declared signal stubs into the hand-written logic file.

The imports line is computed from the Qt classes the page actually uses, so the
generated file imports exactly what it needs and nothing more.
"""
from __future__ import annotations
import os
import textwrap

from .base import CodegenBackend, pyside_qt_prop_lines
from ..core.model import DesignPage
from ..core import sanitize
from ..core import app_theme as app_theme_mod
from ..core import animations as anim_mod
from ..core import sizing as sizing_mod

UI_TEMPLATE = '''# -*- coding: utf-8 -*-
"""
Auto-generated by PaperLoom. Do not edit by hand - regenerate from the design instead.
"""
{core_import}{gui_import}from PySide6.QtWidgets import {imports}

import app_theme

EXTRA_QSS = """{extra_qss}"""
{asset_helper}

class Ui_{cls}:
    def setupUi(self, MainWindow):
        MainWindow.setWindowTitle("{title}")
        MainWindow.resize({width}, {height})
        # follow the OS light/dark by default; EXTRA_QSS is any custom stylesheet
        app_theme.apply(MainWindow, EXTRA_QSS)
{window_sizing}
{setup_body}

    def toggle_theme(self, MainWindow):
        """Cycle this window light -> dark -> system. Returns the new mode."""
        return app_theme.toggle(MainWindow, EXTRA_QSS)

    def set_theme(self, MainWindow, mode):
        """Set the theme: 'light', 'dark' or 'system' (follow the OS)."""
        return app_theme.set_mode(MainWindow, mode, EXTRA_QSS)

    def retranslateUi(self, MainWindow):
        pass
'''

LOGIC_TEMPLATE = '''# -*- coding: utf-8 -*-
"""
Hand-written logic for {cls}. PaperLoom will not overwrite this file -
regenerating the design only ever touches {ui_module}.py.
"""
import sys
from PySide6.QtWidgets import QApplication, QMainWindow

from {ui_module} import Ui_{cls}


class {cls}(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_{cls}()
        self.ui.setupUi(self)
{signal_wiring}

    def toggle_theme(self):
        """Switch this app between light and dark mode."""
        return self.ui.toggle_theme(self)


{stub_methods}
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = {cls}()
    window.show()
    sys.exit(app.exec())
'''


def _snake(name: str) -> str:
    return "".join("_" + c.lower() if c.isupper() else c for c in name).lstrip("_")


class PySideBackend(CodegenBackend):
    target = "pyside6"
    app_theme = app_theme_mod.AppTheme()
    animations = None      # AnimationSet
    extra_stylesheets = ()  # list of raw QSS strings appended after the theme

    def generate(self, page: DesignPage, target_dir: str) -> dict:
        self.warnings = []
        anims = self.animations or anim_mod.AnimationSet()
        cls = page.name
        ui_module = f"{_snake(page.name)}_ui"

        setup_lines, signal_lines, stub_blocks, used_classes = [], [], [], set()
        needs_qt_core = False
        core_extra = set()           # QtCore classes beyond Qt (QDate, QTime, ...)
        gui_imports = set()          # QtGui classes media widgets need
        gen_dir = os.path.join(target_dir, "generated", "pyside6")

        for dw in page.widgets:
            component = self.registry.get(dw.component_id)
            if component is None:
                continue
            used_classes.add(component.qt_include)
            ctx = self._widget_context(dw, component)
            self._attach_asset(dw, ctx, gen_dir)
            fragment = component.render_pyside(ctx)
            if "Qt." in fragment:
                needs_qt_core = True
            if "QDate(" in fragment or "QDate.fromString(" in fragment:
                core_extra.add("QDate")
            if "QTime(" in fragment or "QTime.fromString(" in fragment:
                core_extra.add("QTime")
            if "QTreeWidgetItem(" in fragment:
                used_classes.add("QTreeWidgetItem")
            if "QPixmap(" in fragment or "_fit_pixmap(" in fragment:
                gui_imports.add("QPixmap")
            if "QMovie(" in fragment:
                gui_imports.add("QMovie")
            setup_lines.append(textwrap.indent(fragment.strip("\n"), "        "))
            for line in pyside_qt_prop_lines(dw.object_name, getattr(dw, "qt_props", None)):
                setup_lines.append("        " + line)
            sizing = sizing_mod.sizing_for_widget(dw, component)
            for line in sizing_mod.pyside_lines(dw.object_name, sizing, component):
                setup_lines.append("        " + line)
            if sizing.adaptive:
                used_classes.add("QSizePolicy")
            widget_anims = anims.get(dw.object_name)
            if widget_anims:
                for line in anim_mod.pyside_setup(dw.object_name, widget_anims):
                    setup_lines.append("        " + line)

            for sig in component.signals:
                slot = sig.stub.format(name=dw.object_name)
                signal_lines.append(f"        self.ui.{dw.object_name}.{sig.name}.connect(self.{slot})")
                body = getattr(sig, "body", None) or ""
                if body:
                    stub_blocks.append(
                        f"    def {slot}(self):\n"
                        f"        {body}\n"
                    )
                else:
                    stub_blocks.append(
                        f"    def {slot}(self):\n"
                        f"        # TODO: implement.\n"
                        f'        print("{dw.object_name} {sig.name}")\n'
                    )

        # --- layouts: emit QLayout creation + addWidget for layout-managed widgets ---
        layout_lines = []
        if page.layouts:
            layout_classes = set()
            for lg in page.layouts:
                lc = {"vbox": "QVBoxLayout", "hbox": "QHBoxLayout",
                      "grid": "QGridLayout", "form": "QFormLayout"}.get(lg.kind, "QVBoxLayout")
                layout_classes.add(lc)
                parent = f"self.{lg.parent}" if lg.parent else "MainWindow"
                layout_lines.append(f"        self.{lg.id} = {lc}({parent})")
                layout_lines.append(f"        self.{lg.id}.setSpacing({lg.spacing})")
                l, t, r, b = lg.margins
                layout_lines.append(f"        self.{lg.id}.setContentsMargins({l}, {t}, {r}, {b})")
                # add widgets that reference this layout
                members = sorted(
                    [dw for dw in page.widgets if dw.layout_id == lg.id],
                    key=lambda w: (w.layout_row, w.layout_col))
                for dw in members:
                    if lg.kind == "grid":
                        layout_lines.append(
                            f"        self.{lg.id}.addWidget(self.{dw.object_name}, "
                            f"{dw.layout_row}, {dw.layout_col})")
                    elif lg.kind == "form":
                        layout_lines.append(
                            f"        self.{lg.id}.addRow(self.{dw.object_name})")
                    else:
                        layout_lines.append(
                            f"        self.{lg.id}.addWidget(self.{dw.object_name})")
            used_classes.update(layout_classes)
        if layout_lines:
            setup_lines.extend(["", "        # layouts"] + layout_lines)

        # --- signal/slot connections from the model (Qt Designer style) ---
        connection_lines = []
        for conn in (page.connections or []):
            sender = f"self.{conn.sender}" if conn.sender != "MainWindow" else "MainWindow"
            receiver = f"self.{conn.receiver}" if conn.receiver != "MainWindow" else "MainWindow"
            sig = conn.signal.rstrip("()")
            sl = conn.slot.rstrip("()")
            connection_lines.append(f"        {sender}.{sig}.connect({receiver}.{sl})")
        if connection_lines:
            setup_lines.extend(["", "        # connections"] + connection_lines)

        # --- tab order ---
        if page.tab_order and len(page.tab_order) > 1:
            setup_lines.append("")
            setup_lines.append("        # tab order")
            for i in range(len(page.tab_order) - 1):
                a, b = page.tab_order[i], page.tab_order[i + 1]
                setup_lines.append(
                    f"        MainWindow.setTabOrder(self.{a}, self.{b})")

        imports = ", ".join(sorted(used_classes)) if used_classes else "QWidget"
        anim_imports = anim_mod.needs_imports(anims)
        core_names = sorted({"Qt"} if needs_qt_core else set()
                            | core_extra
                            | {n for n in anim_imports if n.startswith("Q") and
                               n in ("QPropertyAnimation", "QEasingCurve", "QPoint")})
        core_import = (f"from PySide6.QtCore import {', '.join(core_names)}\n"
                       if core_names else "")
        gui_import = ""   # QPixmap/QMovie are now imported inside the asset_helper block
        asset_helper = ""
        if gui_imports:
            # resolve bundled assets relative to this file, so the app loads its
            # media no matter what the working directory is
            asset_helper = (
                "\nimport os\n"
                "from PySide6.QtCore import Qt\n"
                "from PySide6.QtGui import QPixmap\n"
                "_HERE = os.path.dirname(os.path.abspath(__file__))\n\n\n"
                "def _asset(rel):\n"
                "    return os.path.join(_HERE, rel)\n\n\n"
                "def _fit_pixmap(path, w, h, mode='contain'):\n"
                "    pm = QPixmap(path) if isinstance(path, str) else path\n"
                "    if pm.isNull(): return pm\n"
                "    if mode == 'stretch': return pm.scaled(w, h, Qt.AspectRatioMode.IgnoreAspectRatio, Qt.TransformationMode.SmoothTransformation)\n"
                "    if mode == 'cover': return pm.scaled(w, h, Qt.AspectRatioMode.KeepAspectRatioByExpanding, Qt.TransformationMode.SmoothTransformation)\n"
                "    if mode == 'center': return pm\n"
                "    if mode == 'scale-down':\n"
                "        if pm.width() <= w and pm.height() <= h: return pm\n"
                "        return pm.scaled(w, h, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)\n"
                "    return pm.scaled(w, h, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)\n"
            )
        if "QGraphicsOpacityEffect" in anim_imports:
            used_classes.add("QGraphicsOpacityEffect")
        window_sizing = "\n".join(
            "        " + line for line in sizing_mod.window_lines(page))
        ui_source = UI_TEMPLATE.format(
            window_sizing=window_sizing,
            extra_qss="\n".join(self.extra_stylesheets or ()),
            core_import=core_import, gui_import=gui_import, asset_helper=asset_helper,
            imports=imports, cls=cls, title=sanitize.escape_string(page.title),
            width=page.width, height=page.height,
            setup_body="\n".join(setup_lines) if setup_lines else "        pass",
        )
        logic_source = LOGIC_TEMPLATE.format(
            cls=cls, ui_module=ui_module,
            signal_wiring="\n".join(signal_lines) if signal_lines else "        pass",
            stub_methods="\n".join(stub_blocks),
        )

        ui_path = os.path.join(gen_dir, f"{ui_module}.py")
        logic_path = os.path.join(gen_dir, f"{_snake(page.name)}.py")

        theme_path = os.path.join(gen_dir, "app_theme.py")

        self._write_generated(ui_path, ui_source)
        self._write_logic_once(logic_path, logic_source)
        # the app theme travels with every generated project: light/dark for free
        self._write_generated(theme_path, app_theme_mod.runtime_module_source(self.app_theme))
        return {"generated": ui_path, "logic": logic_path, "theme": theme_path}
